CREATE TABLE [dbo].[Characters]
(

	[ID] INT NOT NULL PRIMARY KEY IDENTITY,
    [_BASIC INFO_] NCHAR(10) NULL DEFAULT 'OOOO',
    [Name] NVARCHAR(50) NULL, 
    [Race] NVARCHAR(50) NULL, 
    [Class] NVARCHAR(50) NULL, 
    [Background] NVARCHAR(50) NULL, 
    [Height] FLOAT NULL, 
    [Weight] INT NULL,
    [Homeland] NVARCHAR(50) NULL, 
    [Age] INT NULL,
    [Mentality_Alignment] NVARCHAR(50) NULL, 
    [Moral_Alignment] NVARCHAR(50) NULL, 
    [Honor_Alignment] NVARCHAR(50) NULL, 
    [_STATS_] NCHAR(10) NULL DEFAULT 'OOOO', 
    [Vitality] INT NULL, 
    [Concentration] INT NULL, 
    [Endurance] INT NULL, 
    [Strength] INT NULL, 
    [Dexterity] INT NULL, 
    [Resistance] INT NULL, 
    [Intelligence] INT NULL, 
    [Faith] INT NULL, 
    [Arcane] INT NULL, 
    [_ITEMS_] NCHAR(10) NULL DEFAULT 'OOOO', 
    [Stash] TEXT NULL, 
    [Main_Weapon] NVARCHAR(50) NULL, 
    [Secondary_Weapon] NVARCHAR(50) NULL, 
    [Third_Weapon] NVARCHAR(50) NULL, 
    [Armor] NVARCHAR(50) NULL,
    [_SKILLS_] NCHAR(10) NULL DEFAULT 'OOOO', 
    [Main_Skills] TEXT NULL, 
    [Secondary_Skills] TEXT NULL, 
    [Support_Skills] TEXT NULL, 
    [_SPELLS_] NCHAR(10) NULL DEFAULT 'OOOO', 
    [Novice] TEXT NULL, 
    [Apprentice] TEXT NULL, 
    [Journeyman] TEXT NULL, 
    [Expert] TEXT NULL, 
    [Master] TEXT NULL, 
    [_RELATIONSHIPS_] NCHAR(10) NULL DEFAULT 'OOOO', 
    [Family] TEXT NULL, 
    [Friends] TEXT NULL, 
    [Contacts] TEXT NULL, 
    [Rivals] TEXT NULL, 
    [Enemies] TEXT NULL, 
    [_FILES_] NCHAR(10) NULL DEFAULT 'OOOO', 
    [Backstory] NVARCHAR(MAX) NULL, 
    [IMG] NVARCHAR(MAX) NULL, 





)
